vidhanshu/DSA-Hacktoberfest

- Array/Algorithms/JavaScript/selectionSort.js
I have added selection sort in JavaScript language
> Added Selection Sort for JavaScript

- Array/Algorithms/selectionsort.py
this is the code for selction sort
> Selection sort

- Array/Algorithms/JavaScript/sorting/CountSort.js
As Sir You Assigned Issue #27 to Me, I have sent my Pull Request for this issue, Kindly Merge it, Sir.
> Added Count Sort for JavaScript for HacktoberFest

- Array/Algorithms/C++/sorting/quicksort.cpp
quick sort for cpp #21
I have added quick sort implementation in C++ with respect to the above issue.
> #21 Added quick sort in c++

- Array/Algorithms/C++/sorting/insertionSort.cpp
I have added Insertion Sort implementation in C++ with respect to this issue - Implement insertion sort algorithm in c++ #38
> #38 Added Insertion Sort implementation in C++

- Array/Algorithms/JavaScript/sorting/quickSort.js
Kindly review my pr and merge it
Thanks a lot !!
> Added quickSort algo for JS

- Array/Algorithms/C++/sorting/mergesort.cpp
> merge_sort

- Array/Algorithms/Java/sorting/MergeSort.java
I would like to request the maintainer(s) to accept this PR as a part of the hacktoberfest 2022, and also label my PR as a hacktoberfest.
> Code for Merge Sort added

- Array/Algorithms/C++/searching/least_common_ancestor.cpp
Done for the least-common-ancestor👍
> least-common-ancestor

- Array/Algorithms/C++/searching/binary-search.cpp
>  Binary search

- Array/Algorithms/JavaScript/sorting/radixSort.js
Implemented Radix sort using Javascript
Issue: https://github.com/vidhanshu/DSA-Hacktoberfest/issues/64
#hacktoberfest
> Added Radix Sort. 

- Array/Algorithms/JavaScript/sorting/mergeSort.js
isssue: https://github.com/vidhanshu/DSA-Hacktoberfest/issues/77 
I have added Merge sort code for javascript
> Added mergeSort for js

- Stack/Implementation/Java/StackUsingArrays.java
- Stack/Implementation/Java/StackUsingLinkedlist.java
includes using arrays and Linked list
1. deleted the file stack. java (initial file ) under stack/implementation folder
2. replace that file with StackUsingArrays and stackUsingLinkedlist java files
> Added stack implementation in Java

- Array/Algorithms/JavaScript/sorting/heapSort.js
issue:https://github.com/vidhanshu/DSA-Hacktoberfest/issues/83
I have added Heap Sort in JS
> Added Heap Sort in JS

- Linked List/Implementation/Py/LinkedList.py
Hey! I added python code for linked list. kindly accept my PR for hacktoberfest under the label hacktoberfest2022 and hacktoberfest-accepted.
> Linked List

- Array/Implementation/Py/binary_search.py
Have added Binary search algorithm implemented in python. #50
> Binary Search implemented in python 

- Array/Algorithms/JavaScript/sorting/count sort JAVA
added a new file naming count sort in java in algorithm folder.
taking part in hacktoberfest for first time so if there are any changes needed, do ping me.
> Create count sort JAVA

- Array/Algorithms/Py/sorting/heapsort.cpp
> added heap sort in cpp

- Array/Algorithms/Py/sorting/binarysearch_py
>  added binary search in python

- Array/Algorithms/JavaScript/sorting/insertionSort.js
Issue : https://github.com/vidhanshu/DSA-Hacktoberfest/issues/96
I have added insertion sort in JS.
> Added Insertion Sort in  JS
